version: "3.8"

services:
  loki:
    image: grafana/loki:2.9.0
    container_name: loki
    volumes:
      - ./loki-config.yml:/etc/loki/local-config.yml
      - ./data/loki:/loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yml
    restart: unless-stopped

  grafana:
    image: grafana/grafana:10.0.0
    container_name: grafana
    depends_on:
      - loki
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_ROOT_URL=https://logs.myserver.ru
    volumes:
      - ./data/grafana:/var/lib/grafana
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: loki-proxy
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - loki
    restart: unless-stopped
