services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: modx-web
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      APACHE_RUN_USER: www-data
      APACHE_RUN_GROUP: www-data
    working_dir: /var/www/html
    restart: always
    command: ["sh", "-c", "php /var/www/html/migrations/runner.php && apache2-foreground"]

  db:
    image: mysql:8.0.36-oracle
    container_name: modx-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: modx
      MYSQL_USER: modx
      MYSQL_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data:
